version: '3'
services:
  flask:
    build: ./
    container_name: ppbot-backend
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - /Users/maind/PycharmProjects/NewPPBot/
    ports:
      - "5000:5000"
    command: python Flask.py
